# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X6SRC-kg3QoBdOywaR48hrGht-RIVQj
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
from datetime import datetime
import os

# =========================
# CONFIGURAÇÃO DA PÁGINA
# =========================
st.set_page_config(
    page_title="Tech Challenge Fase 4 - IBOVESPA",
    layout="wide"
)

# =========================
# FUNÇÕES DE CARGA
# =========================
@st.cache_data
def carregar_dados():
    df = pd.read_csv("data/Dados Históricos - Ibovespa 2005-2025.csv")
    
    df['Data'] = pd.to_datetime(
        df['Data'],
        format="%d/%m/%Y",
        errors="coerce"
    )
    
    df = df.dropna(subset=['Data'])
    df = df.sort_values('Data')
    
    return df


@st.cache_resource
def carregar_modelo():
    return joblib.load("model/modelo_ibov.pkl")

df = carregar_dados()
modelo = carregar_modelo()

# =========================
# PREPARAÇÃO DOS DADOS
# =========================
df['log_return'] = np.log(df['Fechamento']).diff()
df = df.dropna()

ultimo_fechamento = df['Fechamento'].iloc[-1]

# =========================
# INTERFACE
# =========================
st.title("📈 Previsão do IBOVESPA")
st.markdown("""
Aplicação desenvolvida para o **Tech Challenge – Fase 4 (FIAP / POSTECH)**
Modelo **ARIMA(1,0,0)** treinado sobre **retorno logarítmico** do IBOVESPA.
""")

# =========================
# SIDEBAR
# =========================
st.sidebar.header("⚙️ Parâmetros")
dias_previsao = st.sidebar.slider(
    "Dias para previsão",
    min_value=5,
    max_value=180,
    value=30
)

# =========================
# HISTÓRICO
# =========================
st.subheader("📊 Histórico do IBOVESPA")

fig1, ax1 = plt.subplots(figsize=(10, 4))
ax1.plot(df['Data'], df['Fechamento'], label="Histórico")
ax1.set_xlabel("Data")
ax1.set_ylabel("Pontos")
ax1.legend()
st.pyplot(fig1)

# =========================
# PREVISÃO (LOG RETURN)
# =========================
st.subheader("🔮 Previsão do Modelo")

previsao_log = modelo.forecast(steps=dias_previsao)

datas_futuras = pd.date_range(
    start=df['Data'].iloc[-1],
    periods=dias_previsao + 1,
    freq='B'
)[1:]

# Converter log_return em nível de preço
precos_previstos = [ultimo_fechamento]

for ret in previsao_log:
    precos_previstos.append(precos_previstos[-1] * np.exp(ret))

precos_previstos = precos_previstos[1:]

df_previsao = pd.DataFrame({
    "Data": datas_futuras,
    "Previsao": precos_previstos
})

fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.plot(df['Data'], df['Fechamento'], label="Histórico")
ax2.plot(df_previsao['Data'], df_previsao['Previsao'],
         linestyle="--", label="Previsão")
ax2.set_xlabel("Data")
ax2.set_ylabel("Pontos")
ax2.legend()
st.pyplot(fig2)

# =========================
# MÉTRICAS DO MODELO
# =========================
st.subheader("📈 Métricas do Modelo ARIMA")

col1, col2 = st.columns(2)
col3, col4 = st.columns(2)

# 👉 Use os valores reais do notebook
col1.metric("Acurácia", "52.3%")
col2.metric("Precisão", "51.8%")
col3.metric("Recall", "50.9%")
col4.metric("F1-Score", "51.3%")

st.markdown("""
As métricas foram calculadas a partir da **previsão de direção do mercado**
(ALTA ou BAIXA), conforme validação realizada na **Fase 2 do Tech Challenge**.
""")

# =========================
# MONITORAMENTO (LOG)
# =========================
st.subheader("🗂️ Monitoramento de Uso")

log = {
    "timestamp": datetime.now(),
    "dias_previsao": dias_previsao
}

log_df = pd.DataFrame([log])

os.makedirs("data", exist_ok=True)

log_df.to_csv(
    "data/logs_previsoes.csv",
    mode="a",
    header=not os.path.exists("data/logs_previsoes.csv"),
    index=False
)

st.success("Previsão registrada para monitoramento do modelo ✅")
